"""create vulnerabilities, assets, risk_scores

Revision ID: 662845248f45
Revises: 
Create Date: 2026-09-05 08:03:25.545242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662845248f45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('sensitivity_tier', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('sensitivity_tier BETWEEN 1 AND 3', name='ck_assets_sensitivity_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vulnerabilities',
    sa.Column('cve_id', sa.Text(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.Text(), nullable=True),
    sa.Column('cvss_severity', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('nvd_last_modified', sa.DateTime(), nullable=True),
    sa.Column('kev_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('kev_date_added', sa.Date(), nullable=True),
    sa.Column('kev_due_date', sa.Date(), nullable=True),
    sa.Column('known_ransomware_use', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vendor_project', sa.Text(), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('vulnerability_name', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('cwe_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_index(op.f('ix_vulnerabilities_cvss_score'), 'vulnerabilities', ['cvss_score'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.Text(), nullable=False),
    sa.Column('lef', sa.Float(), nullable=False),
    sa.Column('lm', sa.Float(), nullable=False),
    sa.Column('ale', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerabilities.cve_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'cve_id', name='uq_risk_scores_asset_cve')
    )
    op.create_index(op.f('ix_risk_scores_ale'), 'risk_scores', ['ale'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_ale'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_vulnerabilities_cvss_score'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_table('assets')
    # ### end Alembic commands ###
