"""asset technologies, cvss version, score breakdown

Revision ID: e71bcf858e75
Revises: 662845248f45
Create Date: 2026-09-13 13:59:52.815573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e71bcf858e75'
down_revision: Union[str, None] = '662845248f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Hand-added: the new risk_scores columns are NOT NULL with no default, which
    # Postgres refuses to add while the table has rows. risk_scores holds only
    # derived data (`python -m app.cli rescore` regenerates all of it), so
    # emptying it is safe -- the same move would NOT be OK on vulnerabilities.
    op.execute("DELETE FROM risk_scores")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('technologies', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('risk_scores', sa.Column('matched_technology', sa.Text(), nullable=False))
    op.add_column('risk_scores', sa.Column('tef', sa.Float(), nullable=False))
    op.add_column('risk_scores', sa.Column('exploit_probability', sa.Float(), nullable=False))
    op.add_column('risk_scores', sa.Column('primary_loss', sa.Float(), nullable=False))
    op.add_column('risk_scores', sa.Column('secondary_loss', sa.Float(), nullable=False))
    op.add_column('vulnerabilities', sa.Column('cvss_version', sa.Text(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('affected_products', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('vulnerabilities', sa.Column('required_action', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'required_action')
    op.drop_column('vulnerabilities', 'affected_products')
    op.drop_column('vulnerabilities', 'cvss_version')
    op.drop_column('risk_scores', 'secondary_loss')
    op.drop_column('risk_scores', 'primary_loss')
    op.drop_column('risk_scores', 'exploit_probability')
    op.drop_column('risk_scores', 'tef')
    op.drop_column('risk_scores', 'matched_technology')
    op.drop_column('assets', 'technologies')
    # ### end Alembic commands ###
